---
spring:
  application:
    name: webchatStudy
server:
  context-path: /webchatStudy  #then access  http://localhost:8080/maven01
  port: 8888
#spring:
#  profiles:
#    active: prod
#  datasource:
#    dataSourceClassName: com.mysql.jdbc.Driver #(com.mysql.jdbc.jdbc2.optional.MysqlDataSource)
#    url: jdbc:mysql://localhost:3306/zthtest
#    username: root
#    password: 123456
#    initialSize: 50
#    maxActive: 1000
#    minIdle: 5
#    maxWait: 60000
#    validationQuery: select 1
#    testOnBorrow: false
#    testOnReturn: false
#    testWhileIdle: true
#    poolPreparedStatements: true
#    maxPoolPreparedStatementPerConnectionSize: 50
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 25200000
#    removeAbandoned: true
#    removeAbandonedTimeout: 1800
#    logAbandoned: true
#    filters: stat